### ISSUE TITLE
tracelb parsing functionality

### ISSUE THREAD

**Issue by quirins** [cmand/scamper#3]
Hi,

the code to parse tracelb warts files seems to be missing (it exists in the C code). 
Do you have plans to include it?

Thank you,
Kind regards
Quirin

**Comment by cmand** [comment]
No plans to add MDA, but we'd be happy to pull a patch.  A glance at scamper_tracelb_warts.c indicates that it wouldn't be too difficult.  Let us know if we can help!

**Comment by rlcalmeida** [comment]
I started adding tracelb support here https://github.com/rlcalmeida/scamper/commit/3c4fd01cee0e1810caeb1798255bf024b16c8ccd

I could not find the tracelb output format in the warts documentation, I am doing it based on scamper_tracelb_warts.c but if any reference can be provided it will be of great help. Hope I can send a pull request soon.

**Comment by robertbeverly** [comment]
thanks @rlcalmeida! let us know if you've got a pull request, or if we can help.  would be nice to add.

**Comment by rlcalmeida** [comment]
Did a pull request, @robertbeverly. Please, let me know if we need to fix anything before merging.

**Comment by robertbeverly** [comment]
Merged.  Many thanks!
